<link href="/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="/frontend/css/fontawesome.css" rel="stylesheet">
<link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<link href="/frontend/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
<link href="/frontend/css/navbar-fixed-top.css" rel="stylesheet">
<link href="/frontend/css/style.css" rel="stylesheet">
<?php if($agent->isMobile()): ?> 
    <link href="/frontend/css/style-mobile.css" rel="stylesheet">
<?php endif; ?>
